apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: keycloak
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: 'Preguntar al administrador'
  KC_DB: postgres
  KC_DB_URL: jdbc:postgresql://postgres.keycloak.svc.cluster.local:5432/keycloak
  KC_DB_USERNAME: keycloak
  KC_DB_PASSWORD: 'Preguntar al administrador'
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
